### PR TITLE
CB-8412 

### PR DESCRIPTION
**Pull request by muratsu**
- Created a `npm run jshint` command & integrate into `npm run test`
- Created jshint rules files for spec and rest of the repo
- Added node_module jshint to repo
- Fixed all jshint issues

### CODE REVIEW

**Comment by purplecabbage** [comment]
Latest commit has broken the build.
https://ci.appveyor.com/project/Humbedooh/cordova-wp8/build/1.0.99

**Comment by muratsu** [comment]
We were previously using sync exec with shelljs. Looks like it was causing a time out as noted [here](http://documentup.com/arturadib/shelljs#command-reference/exec-command-options-callback). Converted them to async to fix the issue. Waiting for the next pass.

**Comment by muratsu** [comment]
Turns out the build errors are unrelated. I'm seeing the following error on Appveyor console:
`C:\Program Files (x86)\MSBuild\Microsoft\WindowsPhone\v8.0\Microsoft.WindowsPhone.Common.targets(110,5): error : The Silverlight 4 SDK is not installed.` I'll open a separate INFRA issue, in the mean time can we go ahead with the merge. Lint changes are hard to rebase later.

**Comment by purplecabbage** [comment]
Infra has nothing to do with appveyor other than setting up the github integration.

**Comment by muratsu** [comment]
Hmm, who owns the test machine? I thought it was owned by infra, I couldn't find a way to configure it. It currently doesnt have Silverlight installed but looks like a week ago it had it.

**Comment by purplecabbage** [comment]
Not sure where you are seeing this error ... I see nothing in any of the failed build logs about Silverlight.

**Comment by muratsu** [comment]
On build 103 you can see this error message: https://ci.appveyor.com/project/Humbedooh/cordova-wp8/build/1.0.103
In order to see the failure, you have to pipe build output to test output, which is not desirable under normal circumstances - that's why I've changed it back to silent and it's not visible on 104.

**Comment by vladimir-kotikov** [comment]
This is an issue of AppVeyor itself and it should be [fixed now](http://help.appveyor.com/discussions/questions/921-support-for-silverlight-4-available). We need just another commit now to trigger the build.

**Comment by muratsu** [comment]
Ahh, finally we're all green on AppVeyor :rocket:

**Pull request merged**
