### PR TITLE
JsonHelper testing, and use of Newtonsoft.Json library to compile/decompile JSON

### PR DESCRIPTION
**Pull request by mowcixo**
When I tried to parse a WSSE security header with **JsonHelper**, I noticed that the **DataContractJsonSerializer** doesn't return the wanted output.

That is because, the WSSE patterns has extra commas and colons in the value string, like that:

```
UsernameToken Username="foo@bar.net", PasswordDigest="ZTQXXXXXXXXXXXXXXXXXXXXXXXXXXXX0NTJlMGE2M2I0NGJiYWM4NA==", Nonce="XXXXXXXXXXXXXXXXXXXXXXXXXXXXA==", Created="2014-10-11T18:48:07.232Z"
```

I recommend to delegate the serialization/deserialization of JSON in the library Newtonsoft.Json for performance and a better result.

### CODE REVIEW

**Comment by pietertingly** [comment]
+1 here also. I have issues parsing JSON in Cordova also, only on Windows Phone platform

**Comment by brodybits** [comment]
:+1: Any idea if and when this will be included?

**Comment by mowcixo** [comment]
No one of the main countributors has pronounced about this...

**Comment by robpaveza** [comment]
LGTM.  Was worried about possible compatibility breaks, but that library respects Data Contract attributes.  So, should be g2g.

**Comment by vladimir-kotikov** [comment]
@mowcixo I’ve looked at this PR today and it seems that it doesn’t add a reference to Newtonsoft JSON library to _template’s_ project file. This causes build to fail with the following error: 
```
cordovalib\JSON\JsonHelper.cs(15,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?) [d:\cordova\mobilespec\platforms\wp8\mobilespec.csproj]
```

**Comment by mowcixo** [comment]
@vladimir-kotikov it uses a .gitmodule to do that... I don't know if it is the best way. How do you recommend to do that? Using the .dll directly?

**Comment by vladimir-kotikov** [comment]
`.gitmodule` just adds the sources to codebase, but this is not enough. You have to open template solution in VS and add a reference to corresponding project manually.

**Comment by mowcixo** [comment]
Ok, I will review it... Can a PR be edited?

**Comment by mowcixo** [comment]
Ok @vladimir-kotikov I have already included the Newtonsoft.Json project in the template, can you try if it's all right?

**Comment by brodybits** [comment]
Hi @mowcixo, I tried pulling your `develop` branch into my workarea, generating a test project, and building it with Visual Studio Express 2013 but am getting a bunch of errors. Also, did you see the AppVeyor build failure?

**Comment by mowcixo** [comment]
Hi @brodybits, can you tell me how you generate a test project? I want to try myself...

Respect to AppVeyor build failure, I think is because another thing, maybe my develop branch doesn't have the changes after 12 Oct 2014...

**Comment by brodybits** [comment]
Given a version of `cordova-wp8` checked out (or extracted from a release zip) in the `cordova-wp8` subdirectory, I tried creating my test project using the following command:
```shell
.\cordova-wp8\bin\create JSONTest com.test.jsontest JSONTest
```

then in the `JSONTest` subdirectory you can find `JSONTest.sln` (Visual Studio Solution, File Explorer probably will not show the extension). You should be able to open it by double-clicking. I have Visual Studio Express 2013 installed, which should be good enough just for building and running Cordova apps for the WP8 platform.

To be honest, I am not sure how much more effort we should put into the WP8 version. The Cordova-Windows version at https://github.com/apache/cordova-windows supports building universal Windows apps that work on Windows 8.0/8.1(+) and Windows Phone 8.1(+). Also, the universal Windows version provides a much smoother interface between the Javascript and native libraries including built-in libraries, C++ libraries, and .NET/C# libraries.

**Comment by mowcixo** [comment]
I just pushed another change, to include Newtonsoft.Json by nuget package manager. I think it is the best solution, because, the errors you was getting, those was because of the Newtonsoft.Json self dependences.

The bad side, is that before executing, nuget has to be executed.

I'm aggreed with you about cordova-windows... but to be honest, I've never tried it.

**Comment by vladimir-kotikov** [comment]
@mowcixo, here is another solution for the problem with headers, you described: https://github.com/apache/cordova-plugin-file-transfer/pull/72

**Comment by mowcixo** [comment]
I close this pull request in favor of apache/cordova-plugin-file-transfer#72

**Pull request closed without merging**
